kind: Service
apiVersion: v1
metadata:
  name:  myapp-service
spec:
  type:  NodePort
  ports:
  - name: Service-NodePort
    port:  80
    targetPort:  80
    nodePort: 30100 #30000-32767
  selector:
    app: myapp
    type: frontend